---
title: "Recruitment Comparisons"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(Grym)
source("./Source/prfit.R")
```

```{r, echo=FALSE}
series <- list.files("../2_Parameters/Recruitment_vectors//")

series <- purrr::map(series, ~readRDS(paste0("../2_Parameters/Recruitment_vectors//", .x)))
```


```{r, echo=FALSE}
func <- function(.x){
  .x$pars$r.mean <- .x$R.mean
  .x$pars$r.sd <- .x$R.sd
  return(.x$pars)
}

pars <- map_dfr(series, ~func(.x))
pars$ID<-paste0(round(pars$r.mean,3)," - ",round(pars$r.sd,3))
```

```{r, echo=FALSE}
ggplot(pars,aes(x=M,y=CV))+
  geom_rect(aes(xmin=0.5, xmax=1.1, 
                ymin=0, ymax=10), 
            fill="lightgreen", alpha=0.01)+
  geom_point(shape=16,alpha=0.1)+
    geom_rect(aes(xmin=0.5, xmax=1.1, 
                ymin=0, ymax=10), 
            col="lightgreen", fill=NA)+
  facet_wrap(.~ID)+theme_bw()+
  labs(x="Mortality (M)", y="Recruitment CV")
```

```{r, echo=FALSE}
pars <- pars %>% mutate(state = case_when( 
  M < 0.5 | M > 1.1 ~ 0, 
  M >= 0.5 | M <= 1.1 ~ 1) )

summary <- pars %>% group_by(r.mean, r.sd) %>% 
  summarise(`M mean` = mean(M), 
  `M min` = min(M), 
  `M max` = max(M), 
  `M prop in range` = sum(state)/n()
                                              )

```

```{r, echo=FALSE}
suppressPackageStartupMessages(library(flextable))

flextable(round(summary, 3))
```



```{r, echo=FALSE}
Days <- seq(0,1,length=365+1)
h <- 1/365
ages <- outer(Days,1:7,FUN="+")

ms <- matrix(1,365+1,length(1:7))
Ms <- ctrapz(ms,h) 
Msf <- final(Ms)

```

```{r, echo=FALSE}
vars <- function(.x){
q<-.x$pars %>% 
  rowwise() %>% 
  summarize(as.data.frame(t(prSim(.x$qdist,Msf,n=.x$R.nsurveys,M,CV,r=.x$R.class))),.groups="drop") 
q$r.mean <- .x$R.mean
q$r.sd <- .x$R.sd
q$ID <- paste0(round(q$r.mean,3)," - ",round(q$r.sd,3))
  return(q)}

recs <- map_dfr(series, ~vars(.x))

```

```{r, echo=FALSE}
ggplot(recs,aes(x=mnR,y=vrR))+
  geom_point(alpha=0.1)+
  facet_wrap(.~ID)+theme_bw()+
  geom_point(aes(x=r.mean,y=r.sd^2),col="red")+
  theme_bw()+
  labs(x="Mean Recruitment (mnR)", y="Recruitment Variance (vrR)")
```
